#line 2 "scanner.cpp"

#line 4 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 76
#define YY_END_OF_BUFFER 77
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[274] =
    {   0,
       65,   65,    0,    0,    0,    0,   77,   70,   66,   69,
       67,    1,    2,   55,   56,   70,   65,   61,   64,   63,
       64,   64,   62,   64,   64,   64,   64,   63,   62,   63,
       64,   34,   38,   64,   64,   64,   64,   70,   73,   74,
       75,   72,   71,   54,   65,   65,    0,   65,   61,   64,
       64,   58,   64,   64,   64,   64,   64,    9,   64,   64,
       64,   64,   64,   64,   58,   64,   64,   64,   21,   64,
       64,   59,   64,   64,   64,   32,   64,   64,   64,   64,
       42,   46,   64,   59,   64,   64,   64,   64,   64,   64,
       58,   68,   73,    0,   60,    3,   64,   64,    4,   64,

       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   18,   64,   19,   20,   64,   64,   64,
       59,   64,   64,   64,   64,   64,   64,   64,   64,   37,
       64,   40,   41,   64,   64,   64,   64,   64,   64,   64,
       50,   64,   64,   53,   64,   64,   64,   64,   64,   64,
       64,   64,    8,   64,   64,   64,   59,   12,   13,   57,
       64,   16,   17,   57,   64,   64,   64,   24,   64,   64,
       28,   64,   64,   64,   33,   35,   64,   64,   64,   64,
       64,   47,   48,   64,   49,   51,   64,   64,   64,   64,
       64,   64,    5,    6,    7,   64,   64,   64,   14,   15,

       59,   22,   64,   25,   64,   64,   29,   30,   31,   36,
       64,   64,   44,   45,   64,   64,   64,   64,   64,   64,
       64,   10,   64,   64,   23,   26,   27,   64,   43,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   11,   64,
       64,   64,   64,   64,   52,   59,   64,   59,   64,   59,
       64,   39,   64,   64,   64,   59,   59,   64,   64,   64,
       59,   59,   64,   64,   64,   64,   64,   64,   59,   64,
       64,   59,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    1,    7,    1,    1,
        1,    1,    1,    1,    8,    9,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    1,    1,    1,
        1,   12,    1,    1,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       22,   29,   30,   31,   32,   33,   34,   35,   36,   37,
        1,   38,    1,   39,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   22,   50,   51,   52,   53,
       54,   55,   22,   56,   57,   58,   59,   60,   61,   62,
       63,   64,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[65] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    1,    3,    3,
        4,    1,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    1,    1,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4
    } ;

static const flex_int16_t yy_base[281] =
    {   0,
        0,    0,   62,   63,  129,  118,  105, 1198, 1198, 1198,
     1198, 1198, 1198, 1198,   85,    0,    0,   60,   63,   65,
      109,   67,   71,  156,   84,   82,   94,   86,  114,  207,
       89,  118,  259,  171,  189,  184,  116,   50,    0, 1198,
     1198, 1198, 1198, 1198,    0,   91,    0,    0,  144,   99,
      151,  133,  177,  136,  180,  245,  197,  139,  223,  233,
      272,  174,  218,  277,  249,  286,  291,  297,  313,  293,
      319,  256,  304,  368,  299,  269,  331,  336,  341,  354,
      325,  389,  344,  352,  364,  379,  362,  383,  409,  394,
      416, 1198,    0,    0,    0,  422,  429,  462,  431,  434,

      437,  446,  442,  450,  456,  472,  475,  484,  459,  487,
      499,  503,  514,  444,  512,  517,  522,  525,  528,  530,
      534,  541,  543,  537,  558,  565,  561,  574,  571,  576,
      586,  588,  593,  595,  598,  600,  610,  615,  624,  626,
      602,  628,  636,  638,  640,  643,  652,  656,  658,  665,
      669,  671,  678,  685,  696,  699,  682,  709,  712,  716,
      718,  720,  723,  725,  727,  729,  737,  739,  741,  743,
      747,  749,  751,  753,  755,  764,  769,  766,  778,  781,
      783,  791,  793,  806,  796,  808,  810,  813,  815,  818,
      821,  823,  828,  834,  838,  844,  849,  853,  846,  855,

      861,  864,  872,  876,  878,  881,  883,  885,  887,  890,
      895,  897,  899,  904,  906,  908,  922,  926,  928,  944,
      946,  935,  948,  954,  956,  958,  963,  965,  967,  970,
      977,  982,  986,  991,  997, 1000, 1004, 1010,  973, 1006,
     1020, 1024, 1028, 1030, 1032, 1038, 1042, 1049, 1051, 1054,
     1056, 1058, 1060, 1065, 1069, 1063, 1080, 1082, 1084, 1086,
     1090, 1093, 1102, 1107, 1111, 1113, 1115, 1117, 1121, 1134,
     1124, 1139, 1198, 1183, 1187,   81,   78, 1189, 1193,   74
    } ;

static const flex_int16_t yy_def[281] =
    {   0,
      273,    1,  274,  274,  275,  275,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  276,  277,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  273,  279,  273,
      273,  273,  273,  273,  276,  277,  280,  277,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  273,  279,  276,  280,  278,  278,  278,  278,  278,

      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,

      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,    0,  273,  273,  273,  273,  273,  273,  273
    } ;

static const flex_int16_t yy_nxt[1263] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,    8,   19,   20,   21,   22,   23,   24,   25,   26,
       27,   26,   28,   29,   30,   31,   26,   32,   33,   34,
       35,   36,   26,   37,   26,   26,   26,   38,    8,   26,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   26,   32,   33,   34,   35,   36,   26,
       37,   26,   26,   26,   40,   40,   41,   41,   47,   48,
       49,   47,   48,   47,   48,   47,   48,   95,   51,   47,
       48,   46,   52,   59,   45,   53,   61,   60,   92,   54,
       47,   48,   47,   48,   47,   48,   44,   47,   48,   94,

       48,   77,   47,   48,  273,   62,   51,   47,   48,   69,
       52,   59,   68,   53,   61,   60,   54,   47,   48,   70,
       43,   55,   47,   48,   47,   48,   47,   48,   56,   77,
       78,   43,   62,   91,  273,   57,   58,   69,  273,   68,
       71,   47,   48,   72,   47,   48,   70,   47,   48,   55,
      273,   79,   47,   48,   49,  273,   56,  273,   78,   47,
       48,   91,   57,   58,   47,   48,   96,   71,   63,  273,
       72,   64,  273,   65,  273,   98,   66,  273,   79,   47,
       48,  273,   47,   48,   84,   47,   48,   67,   47,   48,
      109,   85,   47,   48,   96,  273,   63,   47,   48,   64,

      273,   65,   88,  273,   66,   47,   48,   97,  273,   89,
       99,  273,   84,   90,   67,   47,   48,   86,  109,   85,
       73,  273,  103,  273,   87,  273,   47,   48,  273,   74,
       88,   47,   48,   75,   97,  273,   89,   99,  273,   76,
       90,   47,   48,  273,   86,  273,  104,  110,   73,  103,
      273,   87,  105,   47,   48,  273,   74,   47,   48,  273,
       75,  106,  107,  100,   47,   48,   76,   47,   48,  101,
      273,  102,  273,  104,  110,   80,   81,   47,   48,  105,
       47,   48,  273,   82,  273,   47,   48,  273,  106,  107,
       83,  100,  108,  273,   47,   48,  101,  111,  102,   47,

       48,   47,   48,   80,   81,   47,   48,   47,   48,  112,
       82,  113,   47,   48,  115,  273,  114,   83,  273,  118,
      108,   47,   48,  117,  116,  111,  273,   47,   48,  273,
      126,  273,  121,   47,   48,  273,  112,  119,  113,   47,
       48,  115,  273,  114,   47,   48,  118,  273,  120,   47,
       48,  116,   47,   48,  273,  127,  130,  126,  273,  121,
       47,   48,   47,   48,  273,  119,  128,  129,  131,  273,
       47,   48,   47,   48,  137,  120,   47,   48,  273,  132,
      273,  133,  127,  122,  130,  123,  124,   47,   48,  140,
      273,   47,   48,  128,  129,  139,  131,   47,   48,  125,

      138,  137,   47,   48,  134,  273,  132,  135,  133,  141,
      273,  122,  273,  123,  124,  273,  140,   47,   48,  273,
      136,  273,  144,  139,   47,   48,  125,  138,  273,  142,
       47,   48,  134,  143,  273,  135,  141,   47,   48,   47,
       48,  145,   47,   48,  273,   47,   48,  136,  273,  144,
       47,   48,   47,   48,   47,   48,  273,  142,   47,   48,
      143,  273,  150,  151,   47,   48,  154,   47,   48,  145,
       47,   48,  153,  159,  146,  147,  273,  148,  273,  152,
       47,   48,  149,   47,   48,  273,  155,  273,  156,  150,
      151,  273,   47,   48,  154,   47,   48,  157,  273,  153,

      273,  159,  146,  147,  273,  148,  152,   47,   48,  273,
      149,   47,   48,  155,  158,  273,  156,  160,  273,  162,
       47,   48,   47,   48,  157,   47,   48,  273,  161,  163,
       47,   48,  117,   47,   48,  164,   47,   48,   47,   48,
      165,  158,   47,   48,  160,   47,   48,  162,  166,   47,
       48,   47,   48,  273,  167,  161,  273,  163,  273,  168,
      273,  169,  164,  170,  273,  172,   47,   48,  165,   47,
       48,  273,  171,   47,   48,  273,  166,  175,  273,   47,
       48,  167,   47,   48,   47,   48,  168,  173,  273,  169,
      174,  170,  172,  176,   47,   48,   47,   48,  273,  171,

      177,   47,   48,   47,   48,  175,   47,   48,   47,   48,
       47,   48,  178,  273,  173,  179,  273,  174,   47,   48,
      273,  176,  182,   47,   48,  273,  180,  177,  273,  181,
      273,  183,   47,   48,   47,   48,   47,   48,  273,  178,
      184,  273,  185,  179,   47,   48,   47,   48,   47,   48,
      182,   47,   48,  180,  188,  273,  181,  273,  186,  183,
       47,   48,  187,  273,   47,   48,   47,   48,  184,  273,
      185,  189,  191,   47,   48,  190,  273,   47,   48,   47,
       48,  273,  188,  192,  194,  186,   47,   48,  273,  187,
       47,   48,  193,   47,   48,  273,  195,  273,  189,  273,

      191,  273,  190,  273,   47,   48,  273,   47,   48,  273,
      192,  273,  194,  198,  273,  196,  197,   47,   48,  193,
       47,   48,  273,  195,   47,   48,   47,   48,   47,   48,
      200,   47,   48,   47,   48,   47,   48,   47,   48,  273,
      199,  198,  196,  201,  197,   47,   48,   47,   48,   47,
       48,   47,   48,  273,  202,   47,   48,   47,   48,   47,
       48,   47,   48,   47,   48,  273,  206,  199,  203,  204,
      205,  201,   47,   48,   47,   48,  207,   47,   48,  208,
      273,  202,  273,  209,  273,  210,   47,   48,  273,   47,
       48,   47,   48,  206,  273,  203,  204,  205,  211,   47,

       48,   47,   48,  207,   47,   48,  208,  212,  213,  273,
      209,  214,  273,  210,   47,   48,   47,   48,   47,   48,
      273,   47,   48,   47,   48,  211,   47,   48,  218,   47,
       48,   47,   48,  273,  212,  213,   47,   48,  214,  217,
      273,  216,   47,   48,  219,  215,   47,   48,  273,  221,
      273,  220,   47,   48,   47,   48,  218,   47,   48,  273,
      222,   47,   48,   47,   48,  200,  217,  273,  216,   47,
       48,  219,   47,   48,  223,  273,  221,  273,  220,  273,
       47,   48,  273,  224,   47,   48,   47,   48,  222,   47,
       48,   47,   48,   47,   48,   47,   48,  227,   47,   48,

      226,  223,  225,   47,   48,   47,   48,   47,   48,  273,
      224,  228,   47,   48,   47,   48,   47,   48,  273,  229,
      230,  231,  273,  232,  273,  227,  273,  226,  273,  225,
       47,   48,  273,  233,   47,   48,   47,   48,  273,  228,
      273,  235,  236,   47,   48,  273,  229,  273,  230,  231,
      234,  232,   47,   48,   47,   48,   47,   48,  273,  237,
      233,  238,   47,   48,   47,   48,   47,   48,  273,  235,
      236,   47,   48,   47,   48,   47,   48,  234,   47,   48,
      240,   47,   48,  239,  273,   47,   48,  237,  273,  238,
       47,   48,  273,  241,   47,   48,  242,  243,  273,   47,

       48,  273,  244,  246,  273,   47,   48,  240,   47,   48,
      239,  273,   47,   48,   47,   48,  245,  247,   47,   48,
      241,  273,  248,  242,  249,  243,  250,  273,   47,   48,
      244,  246,   47,   48,  251,  273,   47,   48,   47,   48,
       47,   48,  273,  245,  273,  247,   47,   48,  253,  248,
       47,   48,  249,  255,  250,  252,  254,   47,   48,   47,
       48,  251,   47,   48,   47,   48,   47,   48,   47,   48,
      256,   47,   48,   47,   48,  253,  258,   47,   48,  257,
      255,  260,  252,  254,  273,  261,  273,  259,   47,   48,
       47,   48,   47,   48,   47,   48,  273,  256,   47,   48,

      264,   47,   48,  273,  258,  273,  257,  263,  262,  260,
       47,   48,  273,  261,  259,   47,   48,  273,  265,   47,
       48,   47,   48,   47,   48,   47,   48,  273,  264,   47,
       48,  269,   47,   48,  263,  262,  273,  266,  273,  268,
      273,  267,   47,   48,  273,  270,  265,   47,   48,  273,
      272,  273,  273,  273,  271,  273,  273,  273,  273,  269,
      273,  273,  273,  273,  266,  273,  268,  273,  267,  273,
      273,  273,  270,  273,  273,  273,  273,  272,  273,  273,
      273,  273,  271,   39,   39,   39,   39,   42,   42,   42,
       42,   50,   50,   93,  273,   93,   93,    7,  273,  273,

      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273
    } ;

static const flex_int16_t yy_chk[1263] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    3,    4,   18,   18,
       18,   19,   19,   20,   20,   22,   22,  280,   19,   23,
       23,  277,   20,   22,  276,   20,   23,   22,   38,   20,
       26,   26,   25,   25,   28,   28,   15,   31,   31,   46,

       46,   31,   27,   27,    7,   23,   19,   50,   50,   27,
       20,   22,   25,   20,   23,   22,   20,   21,   21,   27,
        6,   21,   29,   29,   37,   37,   32,   32,   21,   31,
       32,    5,   23,   37,    0,   21,   21,   27,    0,   25,
       29,   52,   52,   29,   54,   54,   27,   58,   58,   21,
        0,   32,   49,   49,   49,    0,   21,    0,   32,   51,
       51,   37,   21,   21,   24,   24,   51,   29,   24,    0,
       29,   24,    0,   24,    0,   54,   24,    0,   32,   34,
       34,    0,   62,   62,   34,   53,   53,   24,   55,   55,
       62,   34,   36,   36,   51,    0,   24,   35,   35,   24,

        0,   24,   36,    0,   24,   57,   57,   53,    0,   36,
       55,    0,   34,   36,   24,   30,   30,   35,   62,   34,
       30,    0,   57,    0,   35,    0,   63,   63,    0,   30,
       36,   59,   59,   30,   53,    0,   36,   55,    0,   30,
       36,   60,   60,    0,   35,    0,   59,   63,   30,   57,
        0,   35,   59,   56,   56,    0,   30,   65,   65,    0,
       30,   60,   60,   56,   72,   72,   30,   33,   33,   56,
        0,   56,    0,   59,   63,   33,   33,   76,   76,   59,
       61,   61,    0,   33,    0,   64,   64,    0,   60,   60,
       33,   56,   61,    0,   66,   66,   56,   64,   56,   67,

       67,   70,   70,   33,   33,   68,   68,   75,   75,   66,
       33,   66,   73,   73,   67,    0,   66,   33,    0,   70,
       61,   69,   69,   69,   68,   64,    0,   71,   71,    0,
       75,    0,   73,   81,   81,    0,   66,   71,   66,   77,
       77,   67,    0,   66,   78,   78,   70,    0,   71,   79,
       79,   68,   83,   83,    0,   77,   79,   75,    0,   73,
       84,   84,   80,   80,    0,   71,   78,   78,   80,    0,
       87,   87,   85,   85,   83,   71,   74,   74,    0,   80,
        0,   80,   77,   74,   79,   74,   74,   86,   86,   87,
        0,   88,   88,   78,   78,   86,   80,   82,   82,   74,

       85,   83,   90,   90,   82,    0,   80,   82,   80,   88,
        0,   74,    0,   74,   74,    0,   87,   89,   89,    0,
       82,    0,   90,   86,   91,   91,   74,   85,    0,   89,
       96,   96,   82,   89,    0,   82,   88,   97,   97,   99,
       99,   97,  100,  100,    0,  101,  101,   82,    0,   90,
      103,  103,  114,  114,  102,  102,    0,   89,  104,  104,
       89,    0,  100,  101,  105,  105,  104,  109,  109,   97,
       98,   98,  103,  109,   98,   98,    0,   98,    0,  102,
      106,  106,   98,  107,  107,    0,  105,    0,  106,  100,
      101,    0,  108,  108,  104,  110,  110,  107,    0,  103,

        0,  109,   98,   98,    0,   98,  102,  111,  111,    0,
       98,  112,  112,  105,  108,    0,  106,  110,    0,  112,
      115,  115,  113,  113,  107,  116,  116,    0,  111,  113,
      117,  117,  117,  118,  118,  115,  119,  119,  120,  120,
      118,  108,  121,  121,  110,  124,  124,  112,  119,  122,
      122,  123,  123,    0,  119,  111,    0,  113,    0,  120,
        0,  122,  115,  123,    0,  124,  125,  125,  118,  127,
      127,    0,  123,  126,  126,    0,  119,  127,    0,  129,
      129,  119,  128,  128,  130,  130,  120,  125,    0,  122,
      126,  123,  124,  128,  131,  131,  132,  132,    0,  123,

      129,  133,  133,  134,  134,  127,  135,  135,  136,  136,
      141,  141,  131,    0,  125,  134,    0,  126,  137,  137,
        0,  128,  137,  138,  138,    0,  135,  129,    0,  136,
        0,  138,  139,  139,  140,  140,  142,  142,    0,  131,
      139,    0,  140,  134,  143,  143,  144,  144,  145,  145,
      137,  146,  146,  135,  145,    0,  136,    0,  142,  138,
      147,  147,  143,    0,  148,  148,  149,  149,  139,    0,
      140,  146,  148,  150,  150,  147,    0,  151,  151,  152,
      152,    0,  145,  149,  151,  142,  153,  153,    0,  143,
      157,  157,  150,  154,  154,    0,  152,    0,  146,    0,

      148,    0,  147,    0,  155,  155,    0,  156,  156,    0,
      149,    0,  151,  156,    0,  154,  155,  158,  158,  150,
      159,  159,    0,  152,  160,  160,  161,  161,  162,  162,
      162,  163,  163,  164,  164,  165,  165,  166,  166,    0,
      161,  156,  154,  165,  155,  167,  167,  168,  168,  169,
      169,  170,  170,    0,  166,  171,  171,  172,  172,  173,
      173,  174,  174,  175,  175,    0,  170,  161,  167,  169,
      169,  165,  176,  176,  178,  178,  172,  177,  177,  173,
        0,  166,    0,  174,    0,  177,  179,  179,    0,  180,
      180,  181,  181,  170,    0,  167,  169,  169,  178,  182,

      182,  183,  183,  172,  185,  185,  173,  179,  180,    0,
      174,  181,    0,  177,  184,  184,  186,  186,  187,  187,
        0,  188,  188,  189,  189,  178,  190,  190,  189,  191,
      191,  192,  192,    0,  179,  180,  193,  193,  181,  188,
        0,  187,  194,  194,  190,  184,  195,  195,    0,  192,
        0,  191,  196,  196,  199,  199,  189,  197,  197,    0,
      196,  198,  198,  200,  200,  200,  188,    0,  187,  201,
      201,  190,  202,  202,  197,    0,  192,    0,  191,    0,
      203,  203,    0,  198,  204,  204,  205,  205,  196,  206,
      206,  207,  207,  208,  208,  209,  209,  206,  210,  210,

      205,  197,  203,  211,  211,  212,  212,  213,  213,    0,
      198,  211,  214,  214,  215,  215,  216,  216,    0,  212,
      215,  215,    0,  215,    0,  206,    0,  205,    0,  203,
      217,  217,    0,  216,  218,  218,  219,  219,    0,  211,
        0,  218,  219,  222,  222,    0,  212,    0,  215,  215,
      217,  215,  220,  220,  221,  221,  223,  223,    0,  220,
      216,  221,  224,  224,  225,  225,  226,  226,    0,  218,
      219,  227,  227,  228,  228,  229,  229,  217,  230,  230,
      224,  239,  239,  223,    0,  231,  231,  220,    0,  221,
      232,  232,    0,  228,  233,  233,  230,  231,    0,  234,

      234,    0,  232,  234,    0,  235,  235,  224,  236,  236,
      223,    0,  237,  237,  240,  240,  233,  235,  238,  238,
      228,    0,  236,  230,  237,  231,  238,    0,  241,  241,
      232,  234,  242,  242,  240,    0,  243,  243,  244,  244,
      245,  245,    0,  233,    0,  235,  246,  246,  242,  236,
      247,  247,  237,  244,  238,  241,  243,  248,  248,  249,
      249,  240,  250,  250,  251,  251,  252,  252,  253,  253,
      247,  256,  256,  254,  254,  242,  251,  255,  255,  249,
      244,  254,  241,  243,    0,  255,    0,  253,  257,  257,
      258,  258,  259,  259,  260,  260,    0,  247,  261,  261,

      260,  262,  262,    0,  251,    0,  249,  259,  258,  254,
      263,  263,    0,  255,  253,  264,  264,    0,  263,  265,
      265,  266,  266,  267,  267,  268,  268,    0,  260,  269,
      269,  267,  271,  271,  259,  258,    0,  264,    0,  266,
        0,  265,  270,  270,    0,  268,  263,  272,  272,    0,
      271,    0,    0,    0,  270,    0,    0,    0,    0,  267,
        0,    0,    0,    0,  264,    0,  266,    0,  265,    0,
        0,    0,  268,    0,    0,    0,    0,  271,    0,    0,
        0,    0,  270,  274,  274,  274,  274,  275,  275,  275,
      275,  278,  278,  279,    0,  279,  279,  273,  273,  273,

      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[77] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 4 "scanner.l"
#include "Bison/parser.h"
#include "procedures.h"
#include <QList>

int yylex();
void yyerror(const char *s);
int line=0;
int column = 0;
int previous = 0;
NodeAST *root;
#line 852 "scanner.cpp"

#line 854 "scanner.cpp"

#define INITIAL 0
#define CADENA 1
#define COM 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 88 "scanner.l"

#line 1073 "scanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 274 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1198 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 91 "scanner.l"
{BEGIN CADENA;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 92 "scanner.l"
{BEGIN COM;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 94 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Add;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 95 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Cat;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 96 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Chgrp;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 97 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Chmod;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 98 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Chown;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 99 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Cont;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 100 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Cp;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 101 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Delete;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 102 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Destiny;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 103 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Edit;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 104 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Exec;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 105 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Fdisk;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 106 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Filen;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 107 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_File;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 108 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Find;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 109 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Fit;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 110 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Grp;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 111 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Idn;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 112 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Id;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 113 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Login;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 114 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Logout;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 115 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Loss;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 116 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Mkdir;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 117 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Mkdisk;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 118 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Mkfile;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 119 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Mkfs;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 120 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Mkgrp;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 121 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Mkusr;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 122 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Mount;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 123 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Mv;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 124 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Name;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 125 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_P;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 126 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Path;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 127 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Pause;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 128 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Pwd;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 129 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_R;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 130 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Recovery;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 131 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Ren;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 132 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Rep;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 133 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Rf;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 134 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Rmdisk;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 135 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Rmgrp;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 136 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Rmusr;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 137 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Rm;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 138 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Ruta;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 139 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Size;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 140 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Type;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 141 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Ugo;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 142 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Unit;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 143 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Unmount;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 144 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RW_Usr;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 145 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return SYM_Arrow;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 146 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return SYM_Ampersand;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 147 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return SYM_Hyphen;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 148 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RE_Delete;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 149 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RE_Fit;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 150 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RE_Name;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 151 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RE_Name2;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 152 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RE_Number;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 153 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RE_Type;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 154 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RE_Unit;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 155 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RE_Id;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 156 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RE_Path;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 157 "scanner.l"
{strcpy(yylval.TEXT, yytext); column=26;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 158 "scanner.l"
{column++;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 159 "scanner.l"
{column++;}
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 160 "scanner.l"
{line++; column=0; previous=0;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 161 "scanner.l"
{
                      column=column+previous; previous = strlen(yytext);strcpy(yylval.TEXT, yytext);
                      Procedures::writeError(QString::fromUtf8(" Error Lexico en la Línea: ") + QString::number(line+1) + QString::fromUtf8(" Columna: ") + QString::number(column+1) + QString::fromUtf8(" Token: ") + QString::fromLatin1(yylval.TEXT));
                    }
	YY_BREAK



case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 168 "scanner.l"
{line++; column = 0; BEGIN INITIAL;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 169 "scanner.l"
{ }
	YY_BREAK



case 73:
YY_RULE_SETUP
#line 173 "scanner.l"
{column=column+previous; previous = strlen(yytext); strcpy(yylval.TEXT, yytext); return RE_String;}
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 174 "scanner.l"
{
                        yyerror("unclosed cadena");
                        Procedures::writeError(QString::fromUtf8(" Error Lexico en la Línea: ") + QString::number(line+1) + QString::fromUtf8(" Columna: ") + QString::number(column+1) + QString::fromUtf8(" Token: ") + QString::fromLatin1(yylval.TEXT));
                    }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 178 "scanner.l"
{BEGIN INITIAL;}
	YY_BREAK

case 76:
YY_RULE_SETUP
#line 180 "scanner.l"
ECHO;
	YY_BREAK
#line 1536 "scanner.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CADENA):
case YY_STATE_EOF(COM):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 274 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 274 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 273);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 180 "scanner.l"


